apps/login_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index' ),
    url(r'^login$', views.login, name='login' ),
    url(r'^register$', views.register, name='register' ),
    url(r'^logout$', views.logout, name='logout' ),
    url(r'^showusers/(?P<id>\d*)$', views.showusers, name='showusers' ),
    url(r'^edituser/(?P<id>\d+)$', views.edituser, name='edituser' ),
    url(r'^updateuser/(?P<id>\d+)$', views.updateuser, name='updateuser' ),
    url(r'^deleteuser/(?P<id>\d+)$', views.deleteuser, name='deleteuser' ),
    url(r'^del_user_prompt/(?P<id>\d+)$', views.del_user_prompt, name='del_user_prompt' ),
    url(r'^keep_user/(?P<id>\d+)$', views.keep_user, name='keep_user' ),
]

integration_project/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
    url(r'^', include('apps.login_reg.urls', namespace='users')),
    # url(r'^admin/', admin.site.urls),
]

apps/login_reg/models.py
from __future__ import unicode_literals
from django.db import models
# from ..courses.models import Course
from datetime import datetime, date
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+.[a-zA-Z]*$')
NAME_REGEX = re.compile(r"^[a-zA-Z]{1}'{0,1}[a-zA-Z]+(-?[a-zA-Z]{1}'{0,1}[a-zA-Z]+)?$")
min_age = 13

class UserManager(models.Manager):
    def register(self, **kwargs):
        message_list = []
        today = date.today()
        if not (NAME_REGEX.match(kwargs['first_name']) and NAME_REGEX.match(kwargs['last_name'])):
            message_list.append('Both name fields are required and can contain only letters. (hyphens OK)')
        if not EMAIL_REGEX.match(kwargs['email']):
            message_list.append('Invalid e-mail address entered. Please enter valid email address.')
        elif User.objects.filter(email=kwargs['email']).exists():
            message_list.append('The e-mail address entered already exists in the database.')
        if len(kwargs['password']) < 8:
            message_list.append("Password must be at least eight characters in length")
        elif kwargs['password'] != kwargs['c_password']:
            message_list.append("Password and Password Confirmation do not match.")
        print (kwargs['dob'] == '')
        if kwargs['dob'] == '':
            message_list.append("Date of birth is a required field. You must be {} years of age to register.".format(min_age))
        else :
            dob_date = datetime.strptime(kwargs['dob'], "%Y-%m-%d").date()
            if (dob_date.year + min_age, dob_date.month, dob_date.day) > (today.year, today.month, today.day):
                message_list.append("You must be {} years of age to register.".format(min_age))
        if len(message_list) is 0 :
            pw_hash = bcrypt.hashpw(kwargs['password'].encode(), bcrypt.gensalt())
            user = self.create(first_name=kwargs['first_name'], last_name=kwargs['last_name'], email=kwargs['email'], dob=kwargs['dob'], password=pw_hash)
            activeuser_dict = {'first_name' : user.first_name, 'last_name' : user.last_name, 'email' : user.email, 'dob' : user.dob, 'id' : user.id}
            message_list.append('New User {} {} successfully registered and logged in.'.format(user.first_name, user.last_name))
            return (True, message_list, activeuser_dict )
        else :
            return (False, message_list)

    def login(self, **kwargs):
        message_list = []
        if not EMAIL_REGEX.match(kwargs['email']):
            message_list.append('Invalid e-mail address entered. Please enter valid email address.')
        if len(message_list) == 0:
            if User.objects.filter(email=kwargs['email']).exists():
                user = self.get(email=kwargs['email'])
                if bcrypt.hashpw(kwargs['password'].encode(), user.password.encode()) ==  user.password.encode() :
                    activeuser_dict = {'first_name' : user.first_name, 'last_name' : user.last_name, 'email' : user.email, 'dob' : unicode(user.dob), 'id' : user.id}
                    message_list.append('User {} {} successfully logged in.'.format(user.first_name, user.last_name))
                    return (True, message_list, activeuser_dict)
            message_list.append("Email, Password combination not found.  Check and try again.")
        return (False, message_list)

    def getusers(self, **kwargs):
        if kwargs['id'] == 'all':
            users = list(User.objects.all())
        else :
            users = [self.get(id=kwargs['id'])]
            # course_list = Course.objects.filter(users__contains=kwargs['id'])
            # print course_list
        return users

    def updateuser(self, **kwargs):
        message_list = []
        user = self.get(id=kwargs['id'])
        today = date.today()
        if not (NAME_REGEX.match(kwargs['first_name']) and NAME_REGEX.match(kwargs['last_name'])):
            message_list.append('Both name fields are required and can contain only letters. (hyphens OK). You entered Frist Name : {}  , Last Name  :  {}'.format(kwargs['first_name'],kwargs['last_name']))
        if not EMAIL_REGEX.match(kwargs['email']):
            message_list.append('Invalid e-mail address entered. Please enter valid email address.')
        if bcrypt.hashpw(kwargs['old_password'].encode(), user.password.encode()) ==  user.password.encode() :
            print "old passowrd matched the database"
            if len(kwargs['new_password']) > 0 or len(kwargs['c_new_password']) > 0 :
                if len(kwargs['new_password']) < 8:
                    message_list.append("Password must be at least eight characters in length")
                elif kwargs['new_password'] != kwargs['c_new_password']:
                    message_list.append("Password and Password Confirmation do not match.")
        else:
            message_list.append("Old password did not match recorded password.")
        if kwargs['dob'] == '':
            message_list.append("Date of birth is a required field. You must be {} years of age to register.".format(min_age))
        else :
            dob_date = datetime.strptime(kwargs['dob'], "%Y-%m-%d").date()
            if (dob_date.year + min_age, dob_date.month, dob_date.day) > (today.year, today.month, today.day):
                message_list.append("You must be {} years of age to register.".format(min_age))
        if len(message_list) is 0 :
            if len(kwargs['new_password']) > 0 or len(kwargs['c_new_password']) > 0 :
                pw_hash = bcrypt.hashpw(kwargs['new_password'].encode(), bcrypt.gensalt())
                self.filter(id=kwargs['id']).update(first_name=kwargs['first_name'],last_name=kwargs['last_name'],email=kwargs['email'],updated_at=datetime.now(), dob=kwargs['dob'],password=pw_hash)
            else:
                self.filter(id=kwargs['id']).update(first_name=kwargs['first_name'],last_name=kwargs['last_name'],email=kwargs['email'],updated_at=datetime.now(),dob=kwargs['dob'])
            user = self.get(id=kwargs['id'])
            activeuser_dict = {'first_name' : user.first_name, 'last_name' : user.last_name, 'email' : user.email, 'dob' : unicode(user.dob), 'id' : user.id}
            message_list.append('User {} {} successfully updated.'.format(user.first_name, user.last_name))
            return (True, message_list, activeuser_dict)
        else :
            message_list.append("No updates applied.  Check values and resubmit")
            return (False, message_list)

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)
    dob = models.DateField()
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/login_reg/views.py
from django.shortcuts import render, redirect
from .models import User
from ..courses.models import Course
from django.contrib import messages
from django.urls import reverse
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    return render(request, 'login_reg/index.html' )

def login(request):
    if request.method == 'POST':
        result = User.objects.login(email=request.POST['email'], password=request.POST['password'])
    if result[0] == False :
        for error_message in result[1] :
            messages.error(request, error_message)
        return redirect(reverse( 'users:index' ) )
    else :
        for success_message in result[1] :
            messages.success(request, success_message)
        request.session['activeuser'] = result[2]

        return redirect(reverse( 'courses:index'))

def register(request):
    if request.method == 'POST':
        result = User.objects.register(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], dob=request.POST['dob'], password=request.POST['password'], c_password=request.POST['c_password'])
        print result
        if result[0] == False :
            for error_message in result[1] :
                messages.error(request, error_message)
            return redirect(reverse( 'users:index' ) )
        else :
            for success_message in result[1] :
                messages.success(request, success_message)
            request.session['activeuser'] = result[2]
            return redirect(reverse( 'users:showusers', kwargs={'id': result[2]['id']}))

def showusers(request, id):
    if id == '' :
        request.session['del_user'] = False
        users = User.objects.getusers(id='all')
    else :
        print "id : ",id
        users = User.objects.getusers(id=id)
    user_count = len(users)
    context = {
    'users' : users,
    'user_count': user_count
    }
    return render(request, 'login_reg/user.html', context)

def logout(request):
    request.session.clear()
    request.session['del_user'] = False
    return redirect(reverse( 'users:index' ) )

def edituser(request, id):
    users = User.objects.getusers(id=id)
    context = {
    'users' : users,
    }
    return render(request, 'login_reg/edituser.html', context )

def updateuser(request, id):
    result = User.objects.updateuser(id=id,first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], dob=request.POST['dob'], old_password=request.POST['old_password'], new_password=request.POST['new_password'], c_new_password=request.POST['c_new_password'])
    print result
    if result[0] == False :
        for error_message in result[1] :
            messages.error(request, error_message)
        return redirect(reverse( 'users:edituser', kwargs={'id': id}))
    else :
        for success_message in result[1] :
            messages.success(request, success_message)
        return redirect(reverse( 'users:showusers', kwargs={'id': id}))

def del_user_prompt(request, id):
    request.session['del_user'] = True
    return redirect(reverse( 'users:showusers', kwargs={'id': id}))

def keep_user(request, id):
    request.session['del_user'] = False
    return redirect(reverse( 'users:showusers', kwargs={'id': id}))

def deleteuser(request, id):
    request.session['del_user'] = False
    temp_id = int(id)
    temp_session_id = request.session['activeuser']['id']
    if temp_session_id == temp_id  :
        print "in if statement"
        del request.session['activeuser']
        User.objects.filter(id=id).delete()
        return redirect(reverse( 'users:index' ) )
    User.objects.filter(id=id).delete()
    return redirect(reverse( 'users:showusers', kwargs={'id': ''}))

apps/login_reg/templates/login_reg/edituser.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>django wall</title>
        {% load staticfiles %}
       <link rel="stylesheet" href="{% static 'login_reg/css/master.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <p>Current logged in user is {{request.session.activeuser.first_name }} {{request.session.activeuser.last_name }}. </p>
        <a href="{% url 'users:logout' %}"><button type="button" name="logout">Logout</button></a>
        <form  class='mybutton' action="{% url 'users:showusers' id=users.0.id %}" method="post">{% csrf_token %}<input type="submit" value="Return without saving changes"></form>
        <form  class='mybutton' action="{% url 'users:showusers' id='' %}" method="post">{% csrf_token %}<input type="submit" value="Show all users (no changes will be saved)"></form>
        <hr>
        <h3>Edit {{users.0.first_name }} {{users.0.last_name }}</h3>
        <p>Current password must be entered to implement any changes.</p>
        <form action="{% url 'users:updateuser' id=users.0.id %}" method="post">
            {% csrf_token %}
            <label>First Name :      <br><input type="text"     name="first_name" value="{{users.0.first_name}}">  </label><br>
            <label>Last Name :       <br><input type="text"     name="last_name" value="{{users.0.last_name}}">    </label><br>
            <label>e-mail :          <br><input type="text"     name="email" value="{{users.0.email}}">        </label><br>
            <label>Date of Birth :   <br><input type="date"     name="dob" value="{{users.0.dob|date:"Y-m-d"}}">          </label><br>
            <label>Current Password:         <br><input type="password" name="old_password" >    </label><br>
            <p>If no password change needed leave fields below empty.</p>
            <label>New Password :<br><input type="password" name="new_password" /> </label><br>
            <label>Confirm New Password :<br><input type="password" name="c_new_password" /> </label>
                                     <br><input type="submit"   name="submit" value='Submit'/>
        </form>
        {% if messages %}
        {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
        {% endif %}
    </body>
</html>

apps/login_reg/templates/login_reg/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>django wall</title>
        {% load staticfiles %}
       <link rel="stylesheet" href="{% static 'login_reg/css/master.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <h2>Please login or register to proceed</h2>
        <h2>Login</h2>
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <label>Email :           <br><input type="text"     name="email"      id='email'/>     </label><br>
            <label>Password :        <br><input type="password" name="password"   id='password'/>  </label><br>
                                     <br><input type="submit"   name="submit" value='Submit'/>
        </form>
        <h2>Register</h2>
        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            <label>First Name :      <br><input type="text"     name="first_name">   </label><br>
            <label>Last Name :       <br><input type="text"     name="last_name">    </label><br>
            <label>e-mail :          <br><input type="text"     name="email">        </label><br>
            <label>Date of Birth :   <br><input type="date"     name="dob">          </label><br>
            <label>Password:         <br><input type="password" name="password" >    </label><br>
            <label>Confirm Password :<br><input type="password" name="c_password" /> </label>
                                     <br><input type="submit"   name="submit" value='Submit'/>
        </form>

        {% if messages %}
        {% for message in messages %}
        <p{% if message.tags %} class='{{message.tags}}'{% endif %}>{{ message }}</p>
        {% endfor %}
        {% endif %}
    </body>
</html>

apps/login_reg/templates/login_reg/user.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>django wall</title>
        {% load staticfiles %}
       <link rel="stylesheet" href="{% static 'login_reg/css/master.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <p>Current logged in user is {{request.session.activeuser.first_name }} {{request.session.activeuser.last_name }}. </p>
        <a href="{% url 'courses:index' %}"><button type="button" name="logout">Proceed to Courses</button></a>
        <a href="{% url 'users:logout' %}"><button type="button" name="logout">Logout</button></a>
        {% if user_count == 1 %}
            <form  class='mybutton' action="{% url 'users:showusers' id='' %}" method="post">{% csrf_token %}<input type="submit" value="Show all users"></form>
            <hr>
            {% if messages %}
                {% for message in messages %}
                    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                {% endfor %}
            {% endif %}
            <h2>User Info for {{users.0.first_name }}  {{users.0.last_name }}</h2>
            <p>User ID : {{users.0.id}}</p>
            <p>Email : {{users.0.email}}</p>
            <p>Date of Birth : {{users.0.dob}}</p>
            <a href="{% url 'users:edituser' id=users.0.id %}"><button type="button" name="edit">Edit</button></a>
            <a href="{% url 'users:del_user_prompt' id=users.0.id %}"><button type="button" name="delete">Delete</button></a>
            {% if request.session.del_user %}
                <p>Are you certain you wish to permanantly delete this user?</p>
                <form  class='mybutton' action="{% url 'users:deleteuser' id=users.0.id %}" method="post">{% csrf_token %}<input type="submit" value="Yes, I want to delete this user"></form>
                <form  class='mybutton' action="{% url 'users:keep_user' id=users.0.id %}" method="post">{% csrf_token %}<input type="submit" value="No do not delete"></form>
            {% endif %}
        {% else %}
        <hr>
            <table>
                <tr>
                    <th>ID</th>
                    <th>first name</th>
                    <th>last name</th>
                    <th>email</th>
                    <th>DOB</th>
                    <th>added</th>
                    <th>updated</th>
                    <th class='action'>Action</th>
                </tr>
            {% for user in users %}
                <tr>
                    <th>{{ user.id }}</th>
                    <th>{{ user.first_name}}</th>
                    <th>{{ user.last_name }}</th>
                    <th>{{ user.email }}</th>
                    <th>{{ user.dob }}</th>
                    <th>{{ user.created_at }}</th>
                    <th>{{ user.updated_at}}</th>
                    <th class='action'>
                    <form  class='mybutton' action="{% url 'users:showusers' id=user.id %}" method="post">{% csrf_token %}<input type="submit" value="show"></form>
                    </th>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
    </body>
</html>