apps/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index' ),
    url(r'^add_course$', views.add_course, name='add_course' ),
    url(r'^del_course/(?P<id>\d+)$', views.del_course, name='del_course' ),
    url(r'^del_prompt/(?P<id>\d+)$', views.del_prompt, name='del_prompt' ),
    url(r'^enroll/(?P<id>\d+)$', views.enroll, name='enroll' ),
    # url(r'^show_course/(?P<id>\d+)$', views.show_course, name='show_course' ),
    # url(r'^edit_course/(?P<id>\d+)$', views.edit_course, name='del_course' ),
]

apps/login_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index' ),
    url(r'^login$', views.login, name='login' ),
    url(r'^register$', views.register, name='register' ),
    url(r'^logout$', views.logout, name='logout' ),
    url(r'^showusers/(?P<id>\d*)$', views.showusers, name='showusers' ),
    url(r'^edituser/(?P<id>\d+)$', views.edituser, name='edituser' ),
    url(r'^updateuser/(?P<id>\d+)$', views.updateuser, name='updateuser' ),
    url(r'^deleteuser/(?P<id>\d+)$', views.deleteuser, name='deleteuser' ),
    url(r'^del_user_prompt/(?P<id>\d+)$', views.del_user_prompt, name='del_user_prompt' ),
    url(r'^keep_user/(?P<id>\d+)$', views.keep_user, name='keep_user' ),
]

integration_project/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
    url(r'^', include('apps.login_reg.urls', namespace='users')),
    # url(r'^admin/', admin.site.urls),
]

apps/courses/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_reg.models import User
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[a-zA-Z]+[a-zA-Z-]*[a-zA-Z]+$')

class CourseManager(models.Manager):
    def add_course(self, **kwargs):
        message_list = []
        min_age = 13
        state = False
        if Course.objects.filter(name=kwargs['name']).exists():
            message_list.append('A Course with the same name already exists. Confirm this is a new course and change the name.  If this is replacing the old course of the same name consider updating or deleteing that course.')
        if (len(kwargs['name']) < 5 or len(kwargs['description']) < 10):
            message_list.append('The course name and descriptions are required.  Course name must be no less than 5 characters in length. Description must be no less than 10 characters in length.')
        if len(message_list) is 0 :
            Course.objects.create(name=kwargs['name'], description=kwargs['description'])
            message_list.append('Course {} successfully added'.format(kwargs['name']))
            state = True
        else :
            state = False
        return (state, message_list)

    def all_courses(self):
        all_courses = list(Course.objects.all())
        all_courses = [(course, len(course.users.all())) for course in all_courses]
        return all_courses
    # def login(self, **kwargs):



# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(max_length=1000)
    users = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = CourseManager()

apps/courses/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .models import Course
from ..login_reg.models import User

# Create your views here.
def add_course(request):
    if request.method == 'POST':
        result = Course.objects.add_course(name=request.POST['name'],description=request.POST['description'])
        if result[0] == False :
            for error_message in result[1] :
                messages.error(request, error_message)
        else :
            for success_message in result[1] :
                messages.success(request, success_message)
        return redirect(reverse( 'courses:index' ) )

def index(request):
    all_courses = Course.objects.all_courses()
    context = {
    'all_courses' : all_courses,
    }
    return render(request, 'courses/index.html', context )

def del_prompt(request, id):
    course = Course.objects.get(id=id)
    context = {
    'course' : course
    }
    return render(request, 'courses/delete_prompt.html', context )

def del_course(request, id):
    course = Course.objects.get(id=id)
    Course.objects.filter(id=id).delete()
    return redirect(reverse( 'courses:index' ) )

def enroll(request, id):
    course = Course.objects.get(id=id)
    print course.name
    user = User.objects.get(id = request.session['activeuser']['id'])
    print user
    print user.id
    print user.first_name, user.last_name
    course.users.add(user)
    course.save()
    all_c_enrollee = course.users.all()
    print course.users
    print "c enrollees:", all_c_enrollee
    return redirect(reverse( 'users:showusers', kwargs={'id': request.session['activeuser']['id']}))

apps/courses/templates/courses/delete_prompt.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Delete </title>
    </head>
    <body>
        <h2>Are you certain you wish to permanantly delete the following course?</h2>
        <p>Name         : {{course.name}}</p>
        <p>Description  : {{course.description}}</p>
        <form  class='mybutton' action="{% url 'courses:index'%}" method="get">{% csrf_token %}<input id={{ course.id }} type="submit" name="{{ course.id }}" value="No do not delete"></form>
        <form  class='mybutton' action="{% url 'courses:del_course' id=course.id %}" method="post">{% csrf_token %}<input id={{ course.id }} type="submit" name="{{ course.id }}" value="Yes, I want to delete this course"></form>

    </body>
</html>

apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Courses</title>
        {% load staticfiles %}
       <link rel="stylesheet" href="{% static 'courses/css/master.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <p class="rightalign">Current User: {{request.session.activeuser.first_name}} {{request.session.activeuser.last_name}}   <a href="{% url 'users:logout' %}"><button type="button" name="logout">Logout</button></a></p>
        {% if messages %}
                {% for message in messages %}
                    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                {% endfor %}
        {% endif %}
        <h3>Add a new course</h3>
        <form action="{% url 'courses:add_course' %}" method="post">
            {% csrf_token %}
            <label>Name :           <br><input type="text"     name="name"      id='name'/>     </label><br>
            <label>Description :     <br><textarea name="description"  rows="8" cols="40" id='description'>  </textarea>
                                     <br><input type="submit"   name="submit" value='Add'/>
        </form>
        {% if messages %}
            {% for message in messages.error %}
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        {% endif %}

        <table>
          <tr>
            <th>ID</th>
            <th>Course Name</th>
            <th>Description</th>
            <th>Number Enrolled</th>
            <th class='action'>Action</th>
          </tr>
          {% for course in all_courses %}
          <tr>
            <th>{{ course.0.id }}</th>
            <th>{{ course.0.name }}</th>
            <th>{{ course.0.description }}</th>
            <th>{{  course.1 }}</th>
            <th class='action'>
            <form  class='mybutton' action="{% url 'courses:del_prompt' id=course.0.id %}" method="post">{% csrf_token %}<input id={{ course.0.id }} type="submit" name="{{ course.0.id }}" value="Delete"></form>
            <form  class='mybutton' action="{% url 'courses:enroll' id=course.0.id %}" method="post">{% csrf_token %}<input id={{ course.0.id }} type="submit" name="{{ course.0.id }}" value="Enroll"></form>
            </th>
          </tr>
          {% endfor %}
        </table>
    </body>
</html>